---
- hosts: buildserver
  become: yes
  vars:
    jenkins_java_options: "-Djenkins.install.runSetupWizard=false -Dpermissive-script-security.enabled=true"
    jenkins_plugins:
      - "permissive-script-security"
      - "cloudbees-folder"
      - "antisamy-markup-formatter"
      - "build-timeout"
      - "credentials-binding"
      - "ssh-agent"
      - "timestamper"
      - "ws-cleanup"
      - "ant"
      - "gradle"
      - "junit"
      - "workflow-aggregator"
      - "github-organization-folder"
      - "pipeline-stage-view"
      - "build-pipeline-plugin"
      - "git"
      - "github"
      - "subversion"
      - "ssh-slaves"
      - "matrix-auth"
      - "pam-auth"
      - "ldap"
      - "email-ext"
      - "mailer"

  roles:
    - geerlingguy.java
    - geerlingguy.jenkins

- hosts: buildserver
  become: yes
  tasks:
    - name: Creates .ssh directory
      file:
        path: ~jenkins/.ssh
        state: directory
    - name: Creates .m2 directory
      file:
        path: ~jenkins/.m2
        state: directory
    - name: Creates .docker directory
      file:
        path: ~jenkins/.docker
        state: directory
    - name: Add docker group
      group:
        name: docker
        state: present
    - name: Add jenkins
      user:
        name: jenkins
        append: yes
        group: docker
    - name: copy workshop private key to jenkins .ssh folder for automated deployments
      copy:
        src: ../aws-setup/workshop_ansiblecc_key
        dest: ~jenkins/.ssh/workshop_ansiblecc_key
        mode: 0600
        owner: jenkins
        group: jenkins
    - name: Log into DockerHub for jenkins
      copy:
        src: files/.docker/config.json
        dest: ~jenkins/.docker/config.json
    - name: Restart service jenkins
      service:
        name: jenkins
        state: restarted
