---
- hosts: allservers  # see the inventory file, also includes the build server
  become: yes        # become a sudo user when running this play!
  roles:             # we depend on other roles that install docker
    - angstwad.docker_ubuntu

- hosts: allservers  # see the inventory file
  become: yes
  tasks:
    - name: Add docker group
      group:
        name: docker
        state: present
    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        append: yes
        group: docker
    - name: Creates .docker directory
      file:
        path: ~ubuntu/.docker
        state: directory
    - name: Log into DockerHub for ubuntu
      copy:
        src: files/.docker/config.json
        dest: ~ubuntu/.docker/config.json
